# Usar la imagen oficial de Node.js
FROM node:18

# Configurar directorio de trabajo
WORKDIR /app

# Copiar archivos de definición de dependencias
COPY package.json package-lock.json ./
COPY vite.config.js .

# Instalar dependencias
RUN npm install
RUN ls node_modules/.bin

# Copiar el resto del código fuente
COPY . .

# Exponer el puerto que utiliza Vite
EXPOSE 3000

# Iniciar el servidor de desarrollo
CMD ["npm", "run", "dev"]



