services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: local
      APP_KEY: base64:YOUR_APP_KEY
      APP_DEBUG: true
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: sistema_de_inventario
      DB_USERNAME: root
      DB_PASSWORD: 

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    volumes:
      - .:/app
    ports:
      - "3000:3000"

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: sistema_de_inventario
      MYSQL_ROOT_PASSWORD: SistemaInventario2024!
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

networks:
  default:

volumes:
  db_data: